body:
- type: textarea
  id: Overview
  attributes:
    label: "Overview"
    placeholder: "E.g., Request to celebrate users who complete their profiles at the end of each batch."
  validations:
    required: true
- type: textarea
  id: current-limitations
  attributes:
    label: "Current Limitations"
    placeholder: "E.g., Currently, there is no recognition for users who complete their profiles, which could help motivate others to do the same."
  validations:
    required: true
- type: textarea
  id: why-this-matters
  attributes:
    label: "Why This Matters"
    placeholder: "E.g., Celebrating profile completions will motivate members to finish their profiles, boosting engagement and fostering a more active community."
  validations:
    required: true
- type: textarea
  id: feature requests
  attributes:
    label: "Feature Request"
    placeholder: "E.g., Implement a process which allows us as GAs to celebrate members that finished creating their profiles."
  validations:
    required: true
